### PR TITLE
#8 Consume Get Api Github

### PR DESCRIPTION
**Pull request by lumc03**

### CODE REVIEW

**Review by holgiosalos — COMMENTED** [review]
please merge main branch with this branch and fix the conflicts on package and package-loc files

**Comment by lumc03** [comment]
Hi @holgiosalos I did the merge from the main with the other branch to fix the conflicts on packages, then the pull request was deleted, and it was left as "approved". I don't know if you had already checked the Consume Github Api Get Method and everything was fine. Please let me know if there is something to fix.

**Comment by holgiosalos** [comment]
yeah I think that I was not clear enough hehe, the merge command should have been executed from this branch `first-api-test`. I will let you know tomorrow what are the required changes, then you should update your local repo (git pull on master) create a new branch and upload the fixes on that branch

**Comment by lumc03** [comment]
Hehe, by git pull on master, do you mean delete first-api-testing branch, create a new branch and do the git pull on this branch?

**Comment by lumc03** [comment]
By the way, to continue with the put, post and delete points, should I create a new branch and make the pull request from that new branch?

**Comment by holgiosalos** [comment]
> Hehe, by git pull on master, do you mean delete first-api-testing branch, create a new branch and do the git pull on this branch?

No, I mean main branch. Always that you get approved a PR, you will need to:
- Squash an merge
- Delete the merged branch
- In your local repo, `git checkout main`
- then: `git pull`
- finally, create the new branch to start the following section of the workshop

**Comment by holgiosalos** [comment]
> By the way, to continue with the put, post and delete points, should I create a new branch and make the pull request from that new branch?

No, the pull should be done over the `main` branch, and each section should be performed in a separated branch and in order

**Pull request merged**
